import os
from .common import *


APP_NAME = os.getenv('APP_NAME', 'Weigh-In')
DEBUG = False

WTF_CSRF_SECRET_KEY = os.getenv('WTF_CSRF_SECRET_KEY')
SECRET_KEY = os.getenv('SECRET_KEY')
RECAPTCHA_PUBLIC_KEY = os.getenv('RECAPTCHA_PUBLIC_KEY')
RECAPTCHA_PRIVATE_KEY = os.getenv('RECAPTCHA_PRIVATE_KEY')

SQLALCHEMY_DATABASE_URI = os.getenv('DATABASE_URL')
DEBUG_TB_INTERCEPT_REDIRECTS = False
SQLALCHEMY_TRACK_MODIFICATIONS = False
